#!/bin/sh
# Like ./chrome, plus file access between local files: films that draw local video frames (the UGC A-roll) need an untainted canvas.
exec "$(dirname "$0")/chrome" --allow-file-access-from-files "$@"
